version: "3.8"
services:
  app:
    build: ../.
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ../image:/app/image
    depends_on:
      - db
    restart: always
    command: bash -c "npm run db:migrate && npm run start"
  db:
    image: 'mysql'
    env_file:
      - .env
    